// Input field constants
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD";
export const CHANGE_USERNAME_FIELD = "CHANGE_USERNAME_FIELD";

// -- Async filed constants --
//Movies
export const REQUEST_MOVIES_PENDING = "REQUEST_MOVIES_PENDING";
export const REQUEST_MOVIES_SUCCESS = "REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_FAILED = "REQUEST_MOVIES_FAILED";

// OAuth - Request_token
export const REQUEST_RTOKEN_PENDING = "REQUEST_RTOKEN_PENDING";
export const REQUEST_RTOKEN_SUCCESS = "REQUEST_RTOKEN_SUCCESS";
export const REQUEST_RTOKEN_FAILED = "REQUEST_RTOKEN_FAILED";

// OAuth - Get Account details
export const REQUEST_ACC_PENDING = "REQUEST_ACC_PENDING";
export const REQUEST_ACC_SUCCESS = "REQUEST_ACC_SUCCESS";
export const REQUEST_ACC_FAILED = "REQUEST_ACC_FAILED";

// -- TV SHOWS

// OAuth - Get Account details
export const REQUEST_TV_PENDING = "REQUEST_TV_PENDING";
export const REQUEST_TV_SUCCESS = "REQUEST_TV_SUCCESS";
export const REQUEST_TV_FAILED = "REQUEST_TV_FAILED";

// OAuth - Get Account States
export const REQUEST_STATES_PENDING = "REQUEST_STATES_PENDING";
export const REQUEST_STATES_SUCCESS = "REQUEST_STATES_SUCCESS";
export const REQUEST_STATES_FAILED = "REQUEST_STATES_FAILED";

//WatchList
export const REQUEST_WATCHLIST_PENDING = "REQUEST_WATCHLIST_PENDING";
export const REQUEST_WATCHLIST_SUCCESS = "REQUEST_WATCHLIST_SUCCESS,";
export const REQUEST_WATCHLIST_FAILED = "REQUEST_WATCHLIST_FAILED";

//ADD or Remove from watchlist
export const REQUEST_ADDORREMOVE_PENDING = "REQUEST_ADDORREMOVE_PENDING";
export const REQUEST_ADDORREMOVE_SUCCESS = "REQUEST_ADDORREMOVE_SUCCESS,";
export const REQUEST_ADDORREMOVE_FAILED = "REQUEST_ADDORREMOVE_FAILED";
// Adding or removing movie  from watchList props
export const ADD_TV = "ADD_TV";
export const REMOVE_TV = "REMOVE_TV";

//Search for a tv show
export const REQUEST_SEARCH_PENDING = "REQUEST_SEARCH_PENDING";
export const REQUEST_SEARCH_SUCCESS = "REQUEST_SEARCH_SUCCESS,";
export const REQUEST_SEARCH_FAILED = "REQUEST_SEARCH_FAILED";

//ERRORS
export const ERROR_NO_DATA = "ERROR_NO_DATA";
