// Input field constants
export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD";
export const CHANGE_USERNAME_FIELD = "CHANGE_USERNAME_FIELD";

// -- Async filed constants --
//Movies
export const REQUEST_MOVIES_PENDING = "REQUEST_MOVIES_PENDING";
export const REQUEST_MOVIES_SUCCESS = "REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_FAILED = "REQUEST_MOVIES_FAILED";

// OAuth - Request_token
export const REQUEST_RTOKEN_PENDING = "REQUEST_RTOKEN_PENDING";
export const REQUEST_RTOKEN_SUCCESS = "REQUEST_RTOKEN_SUCCESS";
export const REQUEST_RTOKEN_FAILED = "REQUEST_RTOKEN_FAILED";
